#!/bin/bash

export TERM=xterm-256color

# get system uptime
let upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
let secs=$((${upSeconds}%60))
let mins=$((${upSeconds}/60%60))
let hours=$((${upSeconds}/3600%24))
let days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh %02dm %02ds" "$days" "$hours" "$mins" "$secs"`

# get cpu temps
let cpu="$(cat /sys/class/thermal/thermal_zone0/temp)"
TEMP=$((${cpu}/1000))

# get the load averages read one five fifteen
read one five fifteen rest < /proc/loadavg

echo "$(tput setaf 2)
$(tput sgr0)                      `date +"%A %e %B %Y, %r"`
$(tput setaf 2)     .~~.   .~~.      $(tput sgr0)`uname -snrmo`
$(tput setaf 2)    '. \ ' ' / .'
$(tput setaf 1)     .~ .~~~..~.      $(tput sgr0)Uptime.............: ${UPTIME}
$(tput setaf 1)    : .~.'~'.~. :     $(tput sgr0)Memory.............: `free -m | grep Mem | awk '{ print $7 }'`MB (Free) / `free -m | grep Mem | awk '{ print $2 }'`MB (Total)
$(tput setaf 1)   ~ (   ) (   ) ~    $(tput sgr0)CPU Temp...........: ${TEMP}°C
$(tput setaf 1)  ( : '~'.~.'~' : )   $(tput sgr0)Load Averages......: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
$(tput setaf 1)   ~ .~ (   ) ~. ~    $(tput sgr0)Running Processes..: `ps ax | wc -l | tr -d " "`
$(tput setaf 1)    (  : '~' :  )     $(tput sgr0)SD Free Space......: `df -h | grep -E '^/dev/root' | awk '{ print $4 }'` (`df -h | grep -E '^/dev/root' | awk '{ print $5 }'` used) on /dev/root
$(tput setaf 1)     '~ .~~~. ~'      $(tput sgr0)HDD Free Space.....: `df -h | grep -E '^/dev/sda1' | awk '{ print $4 }'` (`df -h | grep -E '^/dev/sda1' | awk '{ print $5 }'` used) on /dev/sda1
$(tput setaf 1)         '~'          $(tput sgr0)IP Addresses.......: LAN: `hostname -I | awk '{ print $1 }'` WAN: `curl -s https://api.ipify.org`
$(tput sgr0)"
